exclude:
  - assets/site
  - assets/semantic.less
  - assets/theme.config
  - assets/theme.less
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - home
watch_exclude:
  - dist
encoding: UTF-8

plugins:
  - jekyll-paginate

permalink: /:categories/:title
paginate: 5
paginate_path: /post/:num

title: Work Design
tagline: Site Tagline
production_url : https://work.design

navigation:
- url: /category
  title: 文章分类
- url: /post
  title: 博客
- url: /about
  title: 关于我们

lessc: 'date'
